### ISSUE TITLE
Multi-query parameter validation not working

### ISSUE THREAD

**Issue by stojan-jovic** [python-openapi/openapi-core#366]
Validation for query parameter with multiple values (i.e. array values in form-style query expansion) not working, at least from version `0.13.3` of `openapi-core`.

Example request:
```
http://localhost:8000/v1/test?a=1&a=2
```

Appropriate OpenAPI spec to validate above parameters as `a = ['1', '2']`:
```
parameters:
  - in: query
    name: a
    description: Test query parameter.
    schema:
      type: array
      items:
        type: string
    required: true
```

Validation error:
```
openapi_core.unmarshalling.schemas.exceptions.InvalidSchemaValue: Value [['1', '2']] not valid for schema of type array: (<ValidationError: "['1', '2'] is not of type string">,)
```

Till version `0.13.8` it was possible to "cheat" validation by describing schema as:
```
parameters:
  - in: query
    name: a
    description: Test query parameter.
    schema: {}
    required: true
```

Unfortunately, above workaround not working anymore (from version `0.14.0`), but strangely, schema can be described as follows:
```
parameters:
  - in: query
    name: a
    description: Test query parameter.
    schema:
      type: array
      items:
        type: array
        items:
          type: string
    required: true
```

However, this is not proper way to describe query parameter with multiple values and should be fixed!

**Comment by p1c2u** [comment]
It must be something with the integration. I assume you use Falcon one?

**Comment by stojan-jovic** [comment]
Yes, it's Falcon, little older version, `1.4.1`. Could not remember did I test the latest Falcon version, but I will check and report here.

**Comment by stojan-jovic** [comment]
In meantime, I migrated to the latest `openapi-core` version, i.e. `0.19.0`, with latest Falcon integration (`3.1.1`).

Following still working partially:
```
parameters:
  - in: query
    name: a
    description: Test query parameter.
    schema:
      type: array
      items:
        type: array
        items:
          type: string
    required: true
```
"Partially" because it failing if I pass only one  parameter (in all other combinations it working fine).

However, my question again is - why valid OpenAPI 3 description is not supported:
```
parameters:
  - in: query
    name: a
    description: Test query parameter.
    schema:
      type: array
      items:
        type: string
    required: true
```

Falcon properly decodes such request, for example request `/v1/test?a=1&a=2` will be unpacked as `{'a': ['1', '2']}` (Falcon request params), but `openapi-core` reports validation error:
```
openapi_core.validation.schemas.exceptions.InvalidSchemaValue: Value [['1', '2']] not valid for schema of type array: (<ValidationError: "['1', '2'] is not of type 'string'">,)
```

Am I missing something here?

**Comment by stojan-jovic** [comment]
@p1c2u I apologize for making noise, but how can I properly describe multi-value query parameters in OpenAPI 3 spec so that it working fine with `openapi-core` validation with Falcon integration (all the most recent versions)?

It must be that I'm doing something wrong, but not sure what!?

**Comment by p1c2u** [comment]
I think I found the issue. I will prepare fix for that.

**Comment by stojan-jovic** [comment]
Thanks a lot, Arthur, but it still doesn't work for me... I may be missing something, but is this snippet proper description for multi-value query parameters:
```
parameters:
  - in: query
    name: a
    description: Test query parameter.
    schema:
      type: array
      items:
        type: string
    required: true
```
