### ISSUE TITLE
[Bug]: Validation for catch-all route

### ISSUE THREAD

**Issue by litteratum** [python-openapi/openapi-core#975]
### Actual Behavior

I have the following OpenAPI path:
```
/users/{userId}
```

The validation works OK when I use the same Flask route:
```python
@app.route("/users/<userId>", methods=["GET"])
```

But when I use the catch-all route:
```python
@app.route("/<path:path>", methods=["GET"])
```

I get: "Path not found for http://127.0.0.1:5000/{path}".

### Expected Behavior

I expect the library to properly unmarshal/validate requests that come for a Flask's catch-all route.

### Steps to Reproduce

Have a Flask route:
```python
@app.route("/<path:path>", methods=["GET"])
def handle(path):
    _spec.unmarshal_request(
        FlaskOpenAPIRequest(request)
    )
```

And the following OpenAPI path:
```yaml
/users/{userId}:
  get:
    summary: Retrieve a user by ID
    parameters:
      - name: userId
        in: path
        description: The ID of the user to retrieve
        required: true
        schema:
          type: string
```

Finally, make a request:
```bash
curl http://127.0.0.1:5000/users/id1
```

### OpenAPI Core Version

0.19.4

### OpenAPI Core Integration

flask

### Affected Area(s)

unmarshaling, validation

### Anything else we need to know?

I tried the following hack:
```python
request.url_rule.rule = request.path
```

Unfortunately, it does not work for in-path parameters: "Missing required path parameter: userId".

### Would you like to implement a fix?

None
